# Generated by Django 2.1.7 on 2019-04-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_facility'),
    ]

    operations = [
        migrations.DeleteModel(
            name='facility',
        ),
        migrations.AddField(
            model_name='product',
            name='Air_Conditioning',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Barbecue',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Bedside_Locker_Nightstand',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Bikes_for_use',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Closet_Wardrobe',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Computer',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Desk_and_Lamp',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Dresser_Drawers',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Garden',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Gym_at_home',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Hair_dryer',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Parking',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Smoke_alarm',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Wheelchair_Accessible',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='internet',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='kitchen_available',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='welcome_couples',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='welcome_families',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='welcome_irrelevant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='welcome_males',
            field=models.TextField(null=True),
        ),
    ]
