# Generated by Django 2.1.7 on 2019-04-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190412_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='priceTips',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='internet',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='welcome_families',
            field=models.TextField(null=True),
        ),
    ]
