# Generated by Django 2.1.7 on 2019-04-12 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190412_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='priceTips',
        ),
    ]
