# Generated by Django 2.1.7 on 2019-04-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_product_pricetips'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='culture',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='language',
            field=models.TextField(default='', null=True),
        ),
    ]
