# Generated by Django 2.1.7 on 2019-05-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_board_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='detailinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.TextField(default='', null=True)),
                ('location', models.TextField(default='', null=True)),
                ('drop1', models.TextField(default='', null=True)),
                ('drop2', models.TextField(default='', null=True)),
                ('drop3', models.TextField(default='', null=True)),
                ('languageexchangecount', models.TextField(default='', null=True)),
                ('languageexchangeminute', models.TextField(default='', null=True)),
                ('file2', models.CharField(max_length=150, null=True)),
                ('culture', models.TextField(default='', null=True)),
            ],
        ),
    ]
