# Generated by Django 2.1.7 on 2019-05-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_detailinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailinfo',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
