# Generated by Django 2.1.7 on 2019-05-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_detailinfo_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailinfo',
            name='language',
            field=models.TextField(default='', null=True),
        ),
    ]
