# Generated by Django 2.1.7 on 2019-05-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_detailinfo_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='real_price',
            field=models.IntegerField(default=0),
        ),
    ]
