# Generated by Django 2.1.7 on 2019-05-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20190518_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='userid',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
