# Generated by Django 2.1.7 on 2019-05-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20190518_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='gas',
            field=models.TextField(default='', null=True),
        ),
    ]
