# Generated by Django 2.1.7 on 2019-05-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20190523_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='checkin',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='checkout',
            field=models.TextField(default='', null=True),
        ),
    ]
