# Generated by Django 2.1.7 on 2019-05-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20190523_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='dateinterval',
            field=models.TextField(default='', null=True),
        ),
    ]
