# Generated by Django 2.1.7 on 2019-05-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20190525_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Air_Conditioning',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Airport',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Amusement_Park',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Barbecue',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Beach',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Bedside_Locker_Nightstand',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Bikes_for_use',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Bowling',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Carpet_Moquette',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Cinema',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Closet_Wardrobe',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Computer',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Desk_and_Lamp',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Dresser_Drawers',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Fishing',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Fridge',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Garden',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Golf',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Gym',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Gym_at_home',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Hair_dryer',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Health_club',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Hospital',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Library',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Mirror',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Museum',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Park',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Parking',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Patio',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Radio',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Restaurant',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Shopping_Centre',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Smoke_alarm',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Sports_arena',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Swimming',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Swimming_Pool',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='TV',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Tennis',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Wheelchair_Accessible',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='dorm',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='double_room',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='fax',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='internet',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='kitchen_available',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='laundry',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quadruple_room',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='single_room',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='smoking_possible',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='subway_station',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='telephone',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='triple_room',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='vegetarian',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='welcome_couples',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='welcome_families',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='welcome_females',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='welcome_irrelevant',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='welcome_males',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='welcome_students',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='within_a_hour',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='within_two_hours',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='강아지',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='강원도강릉시',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='객실내화장실',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='객실밖화장실',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='경기도',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='경기도고양시',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='경기도광주시',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='경기도김포시',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='경기도부천시',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='경기도성남시',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='경기도수원시',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='경기도안양시',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='경기도양주시',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='경기도양평군',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='경기도오산시',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='경기도용인시',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='경기도의왕시',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='경기도이천시',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='경기도파주시',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='경상남도창원시',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='경상도',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='경상북도경산시',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='고양이',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='공용화장실',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='대구광역시',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='대구광역시동구',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='대구광역시북구',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='며칠_이내',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='몇_시간_이내',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='부산광역시',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='부산광역시부산진구',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='부산광역시사하구',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='부산광역시해운대구',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='서울특별시',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='서울특별시강남구',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='서울특별시강동구',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='서울특별시강북구',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='서울특별시강서구',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='서울특별시구로구',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='서울특별시노원구',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='서울특별시도봉구',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='서울특별시동대문구',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='서울특별시동작구',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='서울특별시마포구',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='서울특별시서대문구',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='서울특별시서초구',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='서울특별시성북구',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='서울특별시송파구',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='서울특별시양천구',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='서울특별시영등포구',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='서울특별시용산구',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='서울특별시종로구',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='서울특별시중구',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='서울특별시중랑구',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='어류',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='울산광역시',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='울산광역시남구',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='울산광역시중구',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='인천관역시인천',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='인천광역시',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='인천광역시계양구',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='인천광역시남동구',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='인천광역시부평구',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='인천광역시서구',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='인천광역시연수구',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='인천광역시중구',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='제주도',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='제주도서귀포시',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='제주도제주시',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='충청북도',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='충청북도단양군',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='토끼',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='하루_이내',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='햄스터',
            field=models.TextField(default=0, null=True),
        ),
    ]
