# Generated by Django 2.1.7 on 2019-05-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20190525_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='객실내화장실',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='공용화장실',
            field=models.TextField(null=True),
        ),
    ]
