# Generated by Django 2.1.7 on 2019-05-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20190525_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gas',
            field=models.TextField(default='', null=True),
        ),
    ]
