# Generated by Django 2.1.7 on 2019-05-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_product_gas'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailinfo',
            name='product_id',
            field=models.TextField(default='', null=True),
        ),
    ]
