# Generated by Django 2.1.7 on 2019-05-30 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_detailinfo_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='경기도',
        ),
        migrations.RemoveField(
            model_name='product',
            name='서울특별시',
        ),
    ]
